### ISSUE TITLE
Add the ability to terminate background queries.

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#129]
The application can not fully terminate until the initial backend database load is completed. This load time can approach 2 minutes on commodity hw.

**Comment by dorschs57** [comment]
Verify this is still an issue with the switch to redux and backend caching.

**Comment by jw3** [comment]
Could escape button during splash screen could be implemented here to address part of this?  Escape would kill the application.

There could still be a hang on the UI thread to deal with while rendering the table view.

**Comment by jw3** [comment]
Resolved with async trust #750
