### ISSUE TITLE
Bindings for rules and users

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#168]
- rules
- users
- groups

**Comment by tparchambault** [comment]
The journalctl output. The fapolicyd rules logging changes and fapolicyd start/stops/restarts start just after 1615 in the attached log. The rules file had initially:

allow_syslog perm=any all : dir=/tmp/

which resulted in log events showing the execution of /tmp/my-ls, which did execute successfully.
After changing the rule to:

deny_syslog perm=any all : dir=/tmp/

the log shows the denial events, and the attempt to execute /tmp/my-ls was denied as expected.
My guess is that we'll have to configure systemd to log to syslog as opposed to journald or we code it up to handle both. I doubt if the formating is identical but maybe journalctl has an option for output formatting.

[journalctl.out.txt](https://github.com/ctc-oss/fapolicy-analyzer/files/6903569/journalctl.out.txt)
