### ISSUE TITLE
Verify meaning of the color Yellow on the Analysis screens

### ISSUE THREAD

**Issue by dorschs57** [ctc-oss/fapolicy-analyzer#211]
Revisit the meaning of the color Yellow in the Subject and Object fields of the Policy Analysis tool.  Yellow indicates to the user that its a warning, but is the situation with "partial" access really a warning?

**Comment by jw3** [comment]
This was addressed in dab0b15abc52e505100bff61388f28ef0981211f

@scholarsmate please comment and close

**Comment by jw3** [comment]
After some discussion the change will be to change the following from yellow to pink

> Yellow backgrounds for Subject files in the Analysis screens indicate that the Subject 
> has access only to a defined set of Object files.
>
>Yellow backgrounds for Object files in the Analysis screens indicate that the file can be
> accessed using only a set of defined openmodes (e.g. only for Read (R)).
