### ISSUE TITLE
Add rust fmt config

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#234]
https://rust-lang.github.io/rustfmt

**Comment by tparchambault** [comment]
Did you want anything specific in the toml file? 

Fwiw, I had no luck, enabling 'unstable-features' using either with the `unstable_features = true` config file directive, or the CL option `--unstable-features` passed to `rustfmt` as stated in the link above.

However, if you do want to leverage the unstable features, what appears to work is to add the `+nightly` option to `cargo fmt` while using the config file directive `unstable_features = true`

``
$ cargo +nightly fmt
``

https://github.com/rust-lang/rustfmt/issues/2227 was useful wrt the +nightly option approach. There may be something more current in the wild.

**Comment by jw3** [comment]
Closing as we have no fmt preferences at this time.
