### ISSUE TITLE
Add the ability to remove missing files from the Ancillary Trust Database.

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#237]
Currently, if a resource is removed from the filesystem, and that resource was in the ATDb, the resource will be displayed in yellow on the ATDA tab. This is reasonable, correct, and expected behaviour IMO. What is needed is the ability to remove that resource from the ATDb, once the user is alerted to that missing file, and deems its removal appropriate.

**Comment by tparchambault** [comment]
Just noted that the "On File System:" details textbox doesn't refresh correctly when reselecting the missing file. It does initially display empty which is reasonable behavior. Maybe a text msg stating that the resource/file is missing might provide a better UX or something to that effect.

**Comment by egbicker** [comment]
Currently, I am seeing that if a file is added to the Ancillary Trust Database and then removed, it's entry in the GUI is white (not yellow) with an MTime of "Missing".

Speaking with @tparchambault, I think either a right-click context menu to delete the selected item or a new button that will remove the selected/all missing files would work well. Tom also mentioned that adding or moving the Trust/Untrust/Remove buttons to the new toolbar could be an option.

**Comment by egbicker** [comment]
If I attempt to trust or untrust a file that has since been deleted, I would want a pop-up notification that:
- Tells me it has been deleted from the system 
- Offers me a choice to remove it from the ATDb
- Offers me a choice to remove ALL deleted items from the ATDb
- If I do want to remove items, prompt a confirmation dialog

**Comment by egbicker** [comment]
Removing 1 file: 
- Pop-up Context Menu with a "Remove File" appears (only if the file has been deleted)
- Prompts the user to confirm then removes it from the ATDb
- Avoids confusion of having "Untrust" and "Remove" buttons side by side
