### ISSUE TITLE
Event log parser to support parsing multiple values

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/fapolicy-analyzer#253]
### Problem:
While trying to allow a developer to use the rust compiler (rustc), a log gets generated that looks like this:

```
rule=4 dec=deny_syslog perm=execute uid=1000 gid=190,990,1000 pid=37852 exe=/home/vagrant/.cargo/bin/rustc : path=/home/vagrant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc ftype=application/x-executable trust=0
```

Currently the parser only expects a single numerical value for the `gid`, but fapolicyd emits the primary group as well as ancillary groups which the parser wasn't expecting.  This error blocks the analyzer from loading the file for analysis.

### Steps to reproduce:

1. Install rust:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
2. With fapolicyd running, attempt to execute rustc:
```
~/.cargo/bin/rustc --version
```
3. Generate an event log:
```
journalctl -r | grep -e 'rule=\d+' | cut -d: -f4- | awk '{$1=$1};1' > /tmp/rust-event.log
```
4. Load the event log into the fapolicy-analyzer and on the command line you'll see something like this:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Error { input: ",990,1000 pid=37852 exe=/home/vagrant/.cargo/bin/rustc : path=/home/vagrant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc ftype=application/x-executable trust=0", code: Space })', crates/analyzer/src/log.rs:77:38
```

**Comment by jw3** [comment]
The problem exists for multiple fields
- auid
- uid
- sessionid
- gid
- pid

**Comment by jw3** [comment]
Upon further review the multi support  on the other fields needs implemented for rules only, not events.

On events the gid appears to be the only list-capable field in the event log see the following in fapolicyd

https://github.com/linux-application-whitelisting/fapolicyd/blob/main/src/library/policy.c#L295-L315

That bit of code is interesting though, it looks like there could potentially be a "?" to deal with :eyes:
