### ISSUE TITLE
Publish RHEL8 RPMs

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/fapolicy-analyzer#260]
Right now we only publish Fedora 34 RPMs, but it would be good if we also publish RHEL8 RPMs (and any other targeted platforms) too.  The challenge here is that RHEL instances require RedHat subscriptions (RHSM) that use credentials (secrets) that need to be managed and protected by CI/CD for building of the RHEL RPMs.  How do _the good people_ do this?

**Comment by jw3** [comment]
Take a look at the Universal Baseline Images, UBI 8.
