### ISSUE TITLE
Policykit issue when launching fapolicy-analyzer a second time

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#284]
From fc34 vm

1. Run fapolicy-analyzer
2. Close and run again

```
[vagrant@fedora ~]$ fapolicy-analyzer 
Error executing command as another user: No authentication agent found.
Terminating pkttyagent.
```

**Comment by tparchambault** [comment]
It appears that pkttyagent started because that output text `Terminating pkttyagent.` is conditional and will only run if pkttyagent started and has a pid. Whether it then immediately failed/terminated or did not fully complete it's initialization needs to be determined.

**Comment by tparchambault** [comment]
Re: Scholarsmate's comment:

> [vagrant@rhel8 fapolicy-analyzer]$ pipenv run python -m fapolicy_analyzer.ui
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> loaded system in 10 seconds
> loaded system in 5 seconds

Since the app was started directly and not through the wrapper script this is not pkexec/polkit related. It could be permission related but since the system was loaded w/o complaint, I don't think that's the issue either.

I have seen these WARNING messages previously during general dev work but unfortunately don't remember the underlying issues.

**Comment by tparchambault** [comment]
The above warning messages do not occur when pkexec is not the authenticating parent invoking "python -m fapolicy_analyzer.ui."

**Comment by tparchambault** [comment]
The pkttyagent appears to be not starting and/or does not stay up when the issue occurs. Next step is to enable verbosity in the polkitd daemon to determine what end of the client/server connection is not playing nice. I believe it's available via an env var. Will also look at client code to see if enabling verbosity is available.

**Comment by tparchambault** [comment]
The pkttyagent appears to be not consistently starting and/or does not stay up when the issue occurs. Next step is to enable verbosity in the polkitd daemon to determine what end of the client/server connection is not playing nice. I believe it's available via an env var. Will also look at client code to see if enabling verbosity is available.

**Comment by tparchambault** [comment]
pkttyagent authorization agent does not complete its registration on the dbus prior to the pkexec call that execs the fapolicy-analyzer.

Next step: Leverage the  pkttyagent's fd callback mechanism to signal the fapolicy-analyzer wrapper script that it can proceed to the pkexec.
