### ISSUE TITLE
Normal window dimensions (i.e. non-Full Screen) should be maintained when changing tools.

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#313]
Fapolicy-analyzer starts at a fixed size but resizes when changing from the Trust tool to the Analyze tool. When returning to the Trust tool, the new resized dimensions remain. I believe window dimensions should be maintained regardless of tool selection.

**Comment by egbicker** [comment]
I am not seeing this behavior currently. Here's the process I'm following:
1. Launch the ui (opens in fullscreen)
2. Hit the "Restore Down" (the maximize with 2 rectangles overlapping that doesn't minimize)
3. Tool -> Analyze from Audit Log -> Select tests/data/events0.log
4. No resizing is observed here
5. Tool -> Administer Trust Databases
6. No resizing is observed here

**Comment by tparchambault** [comment]
In the master branch, my experience is now identical to yours except that my instance starts in non-fullscreen mode. Bottom line: I no longer see resizing of the main window as I switch tools, so I vote to close this puppy. Thank you @egbicker !
