### ISSUE TITLE
Fedora 34 rpm installation has an unresolved runtime dependency on redux-py

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#321]
We need to add (at minimum and if available) the redux-py dependency to the spec file. Unfortunately, I could not find the appropriate rpm package name. The dnf searches for 'redux-py' or just 'redux' returned zero matches or no python matches respectively. Is a pip install an allowed alternative? I am also assuming that if it's not available for FC then it is not available for RHEL. This may be an incorrect assumption.

**Comment by jw3** [comment]
Need to vendor it, #242 is tracking.

**Comment by tparchambault** [comment]
Closing. Dup of 242.
