### ISSUE TITLE
Policy Event Analysis Tool needs to refresh when changesets are applied

### ISSUE THREAD

**Issue by dorschs57** [ctc-oss/fapolicy-analyzer#339]
Currently the Policy Event Analysis Tool does not take into account trust changes caused by a changeset being applied.  This is evident when a changeset is generated via the Trust Reconciliation Dialog. If you open the dialog a second time for the same file, the trust status has not changed.  However if you navigate back to the Trust Database Admin Tool, then back to the PEAT the files trust is updated with the changeset.

blocked-by #328

**Comment by dorschs57** [comment]
@egbicker your [issue ](https://github.com/ctc-oss/fapolicy-analyzer/pull/379#issuecomment-1022620879)over on PR #379  got me thinking about this. The refresh operation seems to be pretty fast.  It might be easiest for this ticket to not worry about the changesets in the state and just do a `refresh` after every trust operation is preformed.  That should reload everything using the updated Ancillary Trust Db in the new `System` object.  This might be the fast and easiest way to implement this.

**Comment by egbicker** [comment]
I had a similar thought when I was testing it out and saw that it seemed to take care of what was in this issue.
