### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by sheperdsonbrown** [ctc-oss/fapolicy-analyzer#373]
This may be an easy fix, but I am receiving: Error while finding module specification for 'fapolicy-analyzer.ui' (ModuleNotFoundError: No module named 'fapolicy-analyzer')

After using the python3 -m fapolicy-analyzer.ui command: 

I am not familiar with python virtualenvs

**Comment by dorschs57** [comment]
@sheperdsonbrown  typically that means you haven't built the python bindings.  Try running `python3 setup develop` from the project root.

**Comment by sheperdsonbrown** [comment]
I see, I've followed the docs to do so and ran into another glitch. 

python -m ui                   
```Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/fapolicy-analyzer/fapolicy_analyzer/ui/__main__.py", line 26, in <module>
    from .session_manager import sessionManager
  File "/Users/fapolicy-analyzer/fapolicy_analyzer/ui/session_manager.py", line 25, in <module>
    from locale import gettext as _
ImportError: cannot import name 'gettext' from 'locale'```

**Comment by dorschs57** [comment]
hmm that is probably a relative import issue.  Try running the `python3 -m fapolicy-analyzer.ui` command like you did originally.  I suspect that would work now that you built the bindings.

**Comment by jw3** [comment]
@sheperdsonbrown  we added a Makefile with some common operations.

You should now be able to `make run` now to start the application, and there are several other targets to support development flow.

Right now the Makefile assumes you have `Rust` and `pipenv` installed.

- https://www.rust-lang.org/tools/install
- https://pipenv.pypa.io/en/latest/#install-pipenv-today
