### ISSUE TITLE
Trust classification is not consistent between Trust Admin and Event Analysis tool views

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#394]
Using the source controlled events0.log file (slightly tweaked to be consistent with the version of libc), the libc shared object is classified as trusted within the Trust admin tool but classified as Unknown in the Analysis tool.
A snippet from the Trust admin view:
![trust_tool_libc_view](https://user-images.githubusercontent.com/36828847/151876753-bfa6db4f-dcbe-403e-a1c9-c833a91f2b57.png)

Ditto the Event Analysis tool view:
![UnknownObjectFile](https://user-images.githubusercontent.com/36828847/151876946-87270f69-786a-47ac-854d-780050a7818f.png)

Platform: FC34, git branch: issue-356_refresh-button

**Comment by jw3** [comment]
The images highlight different files.

**Comment by tparchambault** [comment]
You are right. My bad. More reason to have canned tested to run on any system.
