### ISSUE TITLE
vendor_rhel8_py39_dependencies

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#402]
RHEL8's default Python version is 3.6 however this application has moved on to Python 3.9. Some runtime Python39 module dependencies are not available in the current RHEL rpm repos:

- python39-rx
- python39-events
- python39-cairo
- python39-gobject
- python39-more-itertools

The cairo and gobject modules are of the highest importance.

**Comment by tparchambault** [comment]
Successfully duplicated the current Docker based rpm generation process on a RHEL8.5 system, with a fully populated  (wrt vendored submodules: events, rx, more-itertools, pygobject, pycairo.) The last two submodules required the installation of additional devel packages on the generation host.

Resulting rpm correctly installed the fapolicy-analyzer with all missing RHEL8 dependencies. Executed correctly after modifying the wrapper script to explicitly invoke python3.9.

**Comment by jw3** [comment]
No longer vendoring.
