### ISSUE TITLE
Time range selection for policy analysis

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#465]
1.  The temporal filter that is applied to the analysis
2. GUI for configuring the temporal filter

From the prototype document 
![image](https://user-images.githubusercontent.com/1545372/161842402-f52e657c-edd8-4bfc-9ac7-3cfdcf9944c8.png)

It doesn't have to be a graphical time slider, a couple of date fields with text / calendar entry will do.

**Comment by egbicker** [comment]
- Current approach is going to be to add a button to the toolbar on the syslog analysis page
- Clicking this button will open a popup
- Popup will have the date entry fields and sliders
- Confirming will close the pop up then filter the data and redraw the gui as appropriate
