### ISSUE TITLE
Enable rule editing in Text View

### ISSUE THREAD

**Issue by dorschs57** [ctc-oss/fapolicy-analyzer#495]
Enable editing in the Rule Admin tool's Text View so the user can edit rules and deploy the results.

**Comment by jw3** [comment]
I pictured the flow being something like

- User edits text in editor
- User triggers a "compile" action
- Rules are "compiled" using a `RuleChangeset`
- On the `RuleChangeset` you can `set()` the full rule text, and then `get()` the parsed rules that have been populated with `RuleInfo` metadata from the parse/lint.  The changeset does not have to be added to a `System` to do these incremental checks
- Continue along with this process until some a "save" action occurs, at that time the `RuleChangeset` gets applied to the `System`
- User can now deploy the `System`, or more edits can be applied using additional changesets

**Comment by jw3** [comment]
Ok we can stash and access the changeset source string
