### ISSUE TITLE
Backup fapolicyd state before deploying changes

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#52]
Consider backups of
- trust db
-  rules file
- anything else we would change 

Timestamped

**Comment by tparchambault** [comment]
Qs: Would this be pre or post deploy? Or possibly the combined set of the ancillary db and the unapplied changes? Do you envision this backup to be managed by the Rust side of the house or the UI side of the demarc. Does the Rust backend leverage the rules file or is the rules file only used directly by fapolicyd and the handling i.e. backing up, of this file by the fapolicy-analyzer to be more of a convenience operation?

**Comment by dorschs57** [comment]
These backups would be taken pre deploy with the idea that the user could restore them post deploy if there was an issue with the newly deployed version of the trust db.  I'm thinking it would be a snapshot of what the current state of the fapolicyd database is before any changesets are deployed to it.  I believe the rust backend should be managing this, with the UI and CLI giving the user the capability to select a backup location and eventually a way to select backups for restoring.

**Comment by jw3** [comment]
I think it makes sense to say this is an application level concern vs a library level concern.  So the backup of the fapolicyd files happens up in python code, related to the deployment management machinery.

Should produce a manifest of files to be packaged up and produce a gzipped (or bzipped) tarball and track it in an XDG dir.
 
The files that need backed up right now would include
```
/var/lib/fapolicyd/data.mdb
/etc/fapolicyd/fapolicyd.conf
/etc/fapolicyd/fapolicyd.rules
/etc/fapolicyd/fapolicyd.trust
```

The mdb file can grow large, on a system with 25k entries it is 40M,  but it does compress nicely to 1.6M with gz and 1.3 with bz2.

**Comment by jw3** [comment]
I think the scope of this ticket is simply to create the backup.  Applying it can be tackled separately, or could even be a documentation issue to describe where to find it and how to unpack and move the files.  Might not need the application to do it.  Regard less we can defer any fancy restoring for now.
