### ISSUE TITLE
Detect systemd service start/stop events to replace hard coded delays

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#531]
The original implementation used conservative hard coded delays to sync fapolicyd starts/stops {via dbus} with the invocation and termination of the Profiling target executables. The focus at that time was correct functionality however it's time for a quick first pass optimization to improve the end-user experience. We can totally eliminate or minimize the hard coded delays if we wait/block while monitoring systemd's journal for fapolicyd events of interest e.g. wait after starting the fapolicyd profiling instance until journalctl reports that the fapd_profiling.service has started, then invoke the profiling target executable. 

This is not a blocker to the systemd profiler work, and will be done in parallel.

**Comment by jw3** [comment]
This should be able to be done on the backend with a few aditions.

1. Could listen for dbus events
  - would look similar to https://github.com/diwic/dbus-rs/blob/master/dbus/examples/unity_focused_window.rs
2. Register a Python callback with the backend that is called when state changes

We don't have any examples of 2 yet but it should be straightforward.  I'll take a look at this in milestone 8.
