### ISSUE TITLE
UI unresponsive after deployment rollback

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#544]
### To reproduce

1. Add trust changes
2. Deploy
3. Select "No" when asked to keep changes

### Noteworthy

- Usually on the first or second deployment the UI becomes unresponsive.
- Same behavior whether the timer expires or you manually click No.
- Did not encounter issues If the deployment is accepted.
- The rollback of configuration is indeed written to disk (ie. the original is restored).
- The daemon is in active state after the app locks, so it appears to be properly started
- Consistently reproducible on fc34 using `rule-text-write` branch's RPM
- **Did not observe issue on RHEL 8** using the same branch

**Comment by jw3** [comment]
Testing in RHEL and the rollback for both timed and manual is solid.

**Comment by tparchambault** [comment]
@jw3 did not try yet. Reviewed code to refresh my memory how fapd was reloading config files. Also it is a change of state so we are using redux so I'm getting ready to debug inside the bowels of redux.

**Comment by tparchambault** [comment]
Duplicated on FC34

**Comment by tparchambault** [comment]
I can't speak definitely why the UI become unresponsive, but this symptom duplicates what we went through previously when the monitoring and control functionality was added to the fapolicy-analyzer.

Monitoring is accomplished via a separate thread (running in MainWidnow) which requests the status of the on-line fapolicyd through a FapdManager function which invokes a rust level function that communicates with systemd via dbus(?).This is a fairly slow operation with perceivable delay. This monitoring request occurs approx every 5 seconds.

Independent of this monitoring thread is the primary Gtk UI thread which can request start and stop fapolicyd operations, again through the FapdManager, which then leverages rust functions. In the case of start or stop control requests, the rust layer is treated as a black box.

When the monitoring and start/stop control functionality was originally implemented, we often experience similar loss of UI functionality until locking was added around any fapolicyd requests. The monitoring thread locks were non-blocking, i.e. if the lock was available grab it and get the fapd status, if it was not available, just continue and don't worry about updating the GUI status element since monitoring isn't considered a critical function currently.

The UI thread's start and stop control requests (those routed through the FapdManager) on the other hand are considered critical and will block until the lock is available.

Now in this issue, my understanding is that behind the rust wall, we are restarting the on-line fapolicyd instance however no locking is occurring i.e. the available of a lock is only being checked on one control path.  What that implies is that the periodic monitoring request to get status is still occurring consequently we've got two threads (One the UI thread, the second is a child of the UI thread) simultaneous attempt to communicate with systemd.

Solutions:

1. Have the fapolicyd restart occur through the FapdManager's, stop() and start() functions.
2. Move the locks down closer to the fapolicyd control communications at the rust level.

**Comment by tparchambault** [comment]
Ifaik w/fapd up, and the monitoring thread disabled (code commented out), fapd was brought down, and then I observed this dbus error 

```
DEBUG:root:fapd_dbase_cleanup_snapshots()
DEBUG:root:Search Pattern: /root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_*.tgz
DEBUG:root:Glob search results: ['/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220725_180031_298250.tgz', '/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220725_233856_896852.tgz']
ERROR:root:An error occurred trying to deploy the changes. Please try again.: DbusFailure(D-Bus error: Transaction for fapolicyd.service/start is destructive (fapolicyd.service has 'stop' job queued, but 'start' is included in transaction). (org.freedesktop.systemd1.TransactionIsDestructive))
DEBUG:root:disposing of subscription for class DeployChangesetsOp
```

Similarly, the same test, with the monitoring thread running, same end result but fapd stayed up:
```
DEBUG:root:Deploying...
ERROR:root:An error occurred trying to deploy the changes. Please try again.: DbusFailure(D-Bus error: Transaction for fapolicyd.service/start is destructive (fapolicyd.service has 'stop' job queued, but 'start' is included in transaction). (org.freedesktop.systemd1.TransactionIsDestructive))
DEBUG:root:disposing of subscription for class DeployChangesetsOp
```

**Comment by jw3** [comment]
> Consistently reproducible on fc34 using rule-text-write branch's RPM

So, the rule-text-write branch still uses the pipe to reload trust.

@tparchambault you said

> Duplicated on FC34

Which branch were you using?

**Comment by jw3** [comment]
Hmm, it appears this might not be isolated to deployment.  I can reproduce using the System->Start/Stop daemon menu.

**Comment by jw3** [comment]
I am going to track this System->Start/Stop daemon menu issue in separate issue so as to not conflate them, even though one may solve the other.

**Comment by jw3** [comment]
Some behavior is going to vary based on the rules that were deployed, for example if I deploy a `deny perm=any all : all` the status update is going to fail.  I think the key for us is to ensure the UI remains responsive.  

@tparchambault the binding call `Handle#is_active` can raise an exception, do you handle that case in the manager?

**Comment by tparchambault** [comment]
> @tparchambault the binding call `Handle#is_active` can raise an exception, do you handle that case in the manager?

Will check.

**Comment by tparchambault** [comment]
> Which branch were you using?

`rule-text-write branch's RPM`

**Comment by tparchambault** [comment]
> ERROR:root:An error occurred trying to deploy the changes. Please try again.: DbusFailure(D-Bus error: Transaction for fapolicyd.service/start is destructive (fapolicyd.service has 'stop' job queued, but 'start' is included in transaction). (org.freedesktop.systemd1.TransactionIsDestructive))

Wrt the above, in the event D-Bus is not playing well with others, captured a pcap file with multiple app runs. Some deployments w/rollbacks were successful, some deployments failed initially, and some attempts to deploy only stopped fapolicyd. Looking at things w/wireshark currently.

[dbus.capture.zip](https://github.com/ctc-oss/fapolicy-analyzer/files/9191732/dbus.capture.zip)

**Comment by jw3** [comment]
@tparchambault I wonder where the start and stop job is coming from on that branch?

**Comment by tparchambault** [comment]
> @tparchambault I wonder where the start and stop job is coming from on that branch? 

If you are referring to the DBus traffic, I do not know, then again, I'm trying to become literate enough wrt DBus to decode the pcaps. I did see them though; I also saw fapolicyd Start and Stop requests w/"fail" string but did not see anything related to pass or success, so either pass/success is assumed or I don't know enough. Probably  the latter.

First addressing the lack of consistent exception handling related to the is_active() call, and secondarily fix the misplaced lock release. Will push asap.

**Comment by jw3** [comment]
A few points to note (as discussed on phone):
1. There is no dbus/systemd daemon reload occurring on the backend, the backend reloads trust only happen through a fifo pipe signal
2. The status check is not dbus, it is backed with a call to systemctl
3. Depending on the active rules, systemctl could fail in which case the binding function would raise an exception
4. The UI deadlock is not isolated to deployment, it can be recreated through the System menu

**Comment by jw3** [comment]
@tparchambault I did a test build that guarantees that the status check does not throw and can still recreate the issue.  So while your lock issue needs cleaned up, I dont think that is the culprit.  Still looking ....

**Comment by jw3** [comment]
> There is no dbus/systemd daemon reload occurring on the backend, the backend reloads trust only happen through a fifo pipe signal

Foot + Mouth == In the case of deployment this is true.  However for rollback the daemon has to be taken down to ensure we can write the files. 

> I wonder where the start and stop job is coming from on that branch?

That answers that.

> it appears this might not be isolated to deployment. I can reproduce using the System->Start/Stop daemon menu.

This remains unexplained.  If we are lucky it is cleared up when fixing the lock issue in the manager.  That makes more sense on that one since it is the direct interaction.

Closing in on it :grin:

**Comment by tparchambault** [comment]
Dunno yet, but I believe that systemctl does use the dbus. At least it appears that way as I look at busctl.

I haven't figure out how the stop/start is being generated but based on the rust level println output it appears that sometimes the start is not successful:

Two snippets from the verbose output with the non-logging text from the rust level sandwiched in...

```
DEBUG:root:Glob search results: ['/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_110721_184825.tgz', '/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_110924_857064.tgz', '/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_111101_639133.tgz', '/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_173129_042083.tgz']
DEBUG:root:Deleting: /root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_110721_184825.tgz
stopped fapolicyd daemon
starting fapolicyd daemon
DEBUG:root:SessionManager::__autosave_edit_session()
DEBUG:root: Session autosave is disabled/bypassed
DEBUG:root:disposing of subscription for class DeployChangesetsOp
INFO:root:Filtering out paths with embedded whitespace
DEBUG:root:SessionManager::__autosave_edit_session()
DEBUG:root: Session autosave is disabled/bypassed
DEBUG:root:[('/home/toma/Development/fapolicy-analyzer-rpms_relative_to_absolute.zip', 'Add')]
DEBUG:root:Deploying...
...
_Backup_20220726_110924_857064.tgz', '/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_111101_639133.tgz', '/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_173129_042083.tgz', '/root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_174404_428296.tgz']
DEBUG:root:Deleting: /root/.local/share/fapolicy-analyzer/Fapolicyd_Backup_20220726_110924_857064.tgz
stopped fapolicyd daemon
DEBUG:root:disposing of subscription for class DeployChangesetsOp
DEBUG:root:_status(ServiceStatus.FALSE updated
DEBUG:root:monitor_daemon:Dispatch update request
DEBUG:root:on_update_daemon_status(ServiceStatus.FALSE)
DEBUG:root:_update_fapd_status(ServiceStatus.FALSE)
```

**Comment by tparchambault** [comment]
So much for bold high-lighting within a code block. Anyhoo in the second case `starting fapolicyd daemon` was not output by the rust println. 

> This remains unexplained.

I will dig in again tomorrow to try and find the stop/start code. But as I noted above whatever uses systemctl appears to use the underlying dbus. I could be wrong on that, but it wouldn't surprise me if DBus is used to proivide the underlying systemd IPC. In any event, I'm looking through the systemctl source, but the `sudo busctl monitor` traffic bursts appear to be correlated to systemctl requests.

**Comment by jw3** [comment]
#548 closes the deployment section of this.  We should split off another issue, I am just trying to figure out what to call it.

**Comment by jw3** [comment]
Added #563 that specifically identifies the remaining issue.

Also added a branch `debug/no_throw_active_checks` that provides modified bindings that do not raise exceptions to demonstrate the difference in behavior when the status check machinery does not encounter the exception.

**Comment by tparchambault** [comment]
Good work wrt #563

**Comment by tparchambault** [comment]
Maybe, the fapolicy-analyzer automagically moves fapolicyd into `--permissive` mode? Staying on-line with active rules seems like a tough platform to design/code for? Just a crazy thought... It's what I do.
