### ISSUE TITLE
Rolling back deployment discards changes

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#550]
When rolling back a deployment the original system should be written to disk, but the application should continue to function with the modified system.

1. Change some rules
2. Deploy
3. Select No to rollback changes
4. Observe that your edits are lost

I would want to deploy and test my changes, but if I rollback I want to start editing where I left off.  The editor should facilitate a rapid rules development loop.  Write, Validate, Run, Modify, Validate, Run, ...

**Comment by jw3** [comment]
@dorschs57 What are your thoughts on this one?

**Comment by dorschs57** [comment]
We could definitely do that. The code would probably look similar to the `SessionManager.open_edit_session` where we first restore to the checkpoint, and then apply changesets again. If we added that code to the `DeployChangesetsOp.__display_deploy_revert_dialog` it should get us close.
