### ISSUE TITLE
Enhance the rules deployment confirmation message

### ISSUE THREAD

**Issue by dorschs57** [ctc-oss/fapolicy-analyzer#556]
Right now the on the deployment confirmation dialog, the user only gets a count of additions and deletions to the rules set. It would be nice for them to be able to view the full diff of the file. One possible option would be to add a button in the treeview row that currently displays the counts so they could popup a new dialog that displays the full diff text. This might also be part of the larger effort of converting the confirmation dialog over to a full deployment review screen like is mocked up in the wireframes.

**Comment by egbicker** [comment]
@jw3 I am seeing an issue with the `rules_difference` method. If you delete the last rule, that rule will show up as both an addition and a removal.

**Comment by jw3** [comment]
> I am seeing an issue with the `rules_difference` method. If you delete the last rule, that rule will show up as both an addition and a removal.

There is probably a new line that you are not taking into account.

If the diff sees lhs of

```
foo
bar
```

and you diff against rhs
```
foo
```

Your results will vary depending on whether you have the new line on rhs.  If the nl is gone, then its going to report the entire line as a removal and addition of the nl-less version.

See if that lines up with what you are seeing.

Perhaps we should strip nl chars in some cases to prevent unexpected behavior... I dont have time to consider that right now, but if you come up with a scheme create a new issue that describes stripping behavior that would reduce the surprise factor here.
