### ISSUE TITLE
Persist unapplied changes

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#56]
In case of application crash or user not completing in current session we need to persist changes so they can be resumed later.

**Comment by jw3** [comment]
Needs #65

**Comment by tparchambault** [comment]
The first high-level design iteration: 
1. Create another tab to display current ancillary database edit session path/action list.
2. Add UI elements and functionality to save/load above list.
3. Add periodic auto-save capabilities to session to provide rescue/prompted-restore if tool or system issues arise.

**Comment by tparchambault** [comment]
**Functionally completed and operational:**
1. File menu items added (Open, Save, SaveAs, Restore) which provide expected functionality to read/write session data to a json file.
2. Autosaves each ancillary edit operation to a tmp json file [default: /tmp/FaCurrentSession.tmp_<timestamp>.json]. These autosaved tmp files are managed such that only a specified max number are maintained (default: 2) and are fully destroyed on successful application exit. 
3. If any tmp session files are detected on application start, the application assumes that the application or system did not exit gracefully, then notifies and prompts the user to restore the prior session.
 
**Subdividing ticket to ease integration, test generation, and review into the following subtickets:**
1. UI level: Add menu items to Save, SaveAs, Open, and Restore edit sessions, and bind to skeleton callbacks. Additionally add logging and command line option handling capabilities. - issue number TBD
2. Add full session functionality to Open/Save/SaveAs with json files replacing skeleton callbacks. - issue number TBD
3. Add autosave capabilities by writing tmp session json files to disk w/each edit operation. Clean up generated tmp files on successful exit. - issue number TBD
4. Add detection of the interruption of the prior session by discovering session tmp files at start-up. Display a modal dialog with restore options. - issue number TBD

**Known Issues, Additional Tasks, Open Requests**
1. Either the AncillaryTrustDatabaseAdmin or its embedded List object (ATDA/eL) need to address the display of duplicate file basenames with differing paths. Currently resources with identical basenames are considered duplicates.
2. The ATDA/eL UI needs to be extended to distinguish between current state of the Ancillary Trust Database and pending operations. Also needs to display pending Untrusted operations; currently the file is simply removed from the list view.
3. Request: Extend the ATDA/eL API such that it's easier to extract a dictionary/list of tuples/whatever of full path and associated actions, to get a list of the current pending trust operations.
