### ISSUE TITLE
Ensure deployment dialogs are in memory

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#562]
We need to avoid having to load the glade files for deployment dialogs from disk.  It should be preloaded and retained in memory.

```
GLib.Error: g-file-error-quark: Failed to open file “/usr/lib/python3.6/site-packages/fapolicy_analyzer/glade/deploy_confirm_dialog.glade”: Operation not permitted (22)
```

1. Deploy a deny any all all rule
2. Stop the daemon with the System menu
3. Restart the app
4. Start the daemon with the System menu
5. Try to deploy

At step 5 you should observe the error above.

**Comment by jw3** [comment]
I just noticed that this issue is mistitled, it is not the rollback dialog, it is the confirm dialog that generates the error

**Comment by jw3** [comment]
@dorschs57 I just noticed that this issue is mistitled, as its not the rollback dialog, it is the confirm dialog that generates the error

**Comment by dorschs57** [comment]
> @dorschs57 I just noticed that this issue is mistitled, as its not the rollback dialog, it is the confirm dialog that generates the error

ok, I'm working on a solution that should fix the issue for all glade files that need to be loaded.
