### ISSUE TITLE
Added a date modified column to the trust list view

### ISSUE THREAD

**Issue by dorschs57** [ctc-oss/fapolicy-analyzer#61]
Add a column showing the last modified date of the file in the trust list view on the DB admin pages.

**Comment by jw3** [comment]
blocks #60

**Comment by tparchambault** [comment]
On first design iteration, I'm not convinced that the mtime details should be in the file list object itself given the limited UI real-estate we have available there, and given that it is in the 'On File System' details for both the ancillary and system databases.

We can still sort by mtime, and potentially make a column optionally visible.
