### ISSUE TITLE
Add a third status bar icon to address the condition when the fapolicyd service is unavailable.

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#615]
'Unavailable' includes both uninstalled and/or unreachable through the dbus/systemd.

**Comment by tparchambault** [comment]
35f169c4eb6ccf43009a8ceeff13741ab265969f

I suspect this issue was a shortcoming of the above commit.

**Comment by egbicker** [comment]
@jw3 Tom mentioned that there are some specific service names used by the rust layer to communicate with systemd and that not having those or having them with different names would case issues. Do you know where that might be in the rust files?

**Comment by jw3** [comment]
fapolicyd is the only service name to worry about, and it is the default, so you dont need to worry about it.

What concern are you asking about?

**Comment by tparchambault** [comment]
> Tom mentioned that there are some specific service names used by the rust layer to communicate with systemd and that not having those or having them with different names would case issues. Do you know where that might be in the rust files?

@jw3 , I threw the above out to @egbicker when he brought this issue up this AM because I was trying to remember why/when this got created. At one point, you were testing dynamic service/unit file mods/creation and wanted better exception handling or something to that effect, but I think it's the above comment: At the UI level we don't distinguish between `fapolicyd` being off-line and a `systemd` error code, whether it's a dbus comms issue, bad unit file syntax, missing/renamed unit file, etc.

**Comment by jw3** [comment]
The intent of the issue was to represent when the fapolicyd service does not exist.

The python code just needs to represent a third state that rolls up anything other than active or inactive.

**Comment by egbicker** [comment]
@jw3 Spent some cycles on this before trying to run without fapolicyd installed and the main app doesn't even launch for me, I get the "not installed on system" dialog window instead.

Also went and looked at the `systemctl status` page and I'm not seeing what other states other than active or inactive that the service can be in. This issue might be OBE unless I'm missing something

**Comment by jw3** [comment]
The systemd service is the concern.

1. Install fapolicyd 
2. Remove the fapolicyd unit
3. Run the app

**Comment by egbicker** [comment]
@jw3 What is the criteria for the rust `Handler.is_valid()`?
On my test VM:
1. I installed fapolicyd and my branch RPM
2. I removed the fapolicyd unit `rm /usr/lib/systemd/system/fapolicyd.service`
3. I ran my RPM build and had `self._fapd_ref.is_valid` which is `Handler("fapolicyd")` return `True` on start

**Comment by jw3** [comment]
> What is the criteria for the rust Handler.is_valid()?

Query a systemd service via dbus and if that fails the state is invalid, everything otherwise is valid.

> sudo systemctl status fapolicyd returns Unit fapolicyd.service could not be found

This is a good test.  I was going to suggest doing a systemctl daemon-reload after deleting, but doesnt look like you need to.  Though still could try that if you havent.

Ill look at the code involved and see if there is anything obvious.

**Comment by jw3** [comment]
> Ill look at the code involved and see if there is anything obvious.

Yeah, its obviously broken.  The original impl was assuming dbus returned an error if querying for status on a unit that does not exist.  It doesnt, just says inactive.

I have a working impl using the loaded status of the unit def that will be merged for next week.

**Comment by jw3** [comment]
@egbicker #852 should resolve the problems in service code.
