### ISSUE TITLE
A high-level desktop application icon is needed. 

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#616]
Currently on FC after an rpm install, we have the circle with a slash icon dirplayed in the application task bar, and in the Alt-Tab window cycling pop-up.

**Comment by jw3** [comment]
Bumping this to 1.0 in response to feedback from Fedora review in #715

> [?]: Package contains desktop file if it is a GUI application.

**Comment by jw3** [comment]
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_desktop_files
