### ISSUE TITLE
Add UI for fapolicyd stats

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#621]
fapolicyd has support for requesting stats from the daemon on demand at runtime.  This issue is for polling and displaying those stats in the UI.

Another issue is going to add support for collecting cpu and disk usage at the same time to allow overlaying with cache stats to detect hotspots.

- Polling the stats at some interval during regular daemon operation and while profiling.
- Parsing stats from logs or state file.
- Maintaining separate timelines of data points for regular daemon and profiling runs.
- Display updated stats in table like ui component.
- Display line chart that plots stats overlayed with cpu / disk usage across time. (Optional - may be new issue)

**Comment by egbicker** [comment]
Is this available from the backend or does the functionality need to be added to rust first?

**Comment by jw3** [comment]
PR submitted to fapolicyd to allow requesting stats
- https://github.com/linux-application-whitelisting/fapolicyd/pull/284


> Is this available from the backend or does the functionality need to be added to rust first?

Will add Rust impl after the PR is merged/declined.
