### ISSUE TITLE
Finalize how to handle Untrusted vs Unknown files in the UI trust list

### ISSUE THREAD

**Issue by dorschs57** [ctc-oss/fapolicy-analyzer#64]
1. Figure out exactly what it means for a file to be untrusted vs unknown.
    * An untrusted file is one that the user has specifically selected as untrusted in the UI, but has not yet been persisted back to the ancillary trust database?
    * An unknown file is one that either a. has a mismatch in its sha or file size or b. was added from the system trust database?
 1. Develop a good way to visualize with the green/yellow/red and T/U/? indicators the final outcome of #1 above.

**Comment by jw3** [comment]
#73 calls for refactor to T/D/U, defined as

- Trusted; in db and matches
- Discrepancy; in db but does not match
- Untrusted; not in db

**Comment by jw3** [comment]
@dorschs57 are we good on this now given the change to T/D in #104 ?

**Comment by dorschs57** [comment]
I'd say we are good to close this ticket.  If we get different feedback in the future we can open a new ticket. 👍
