### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#668]
Many errors encountered in the UI are presented with a toaster popup, but then there is nothing else to indicate what happened.

Need to write a log to disk.  Could be a couple of logs, one for backend and one for front, if that is significantly simpler.

**Comment by tparchambault** [comment]
Based on the Status/Design meeting discussion, 1st iteration goals (to bwe revisited, if needed):
1. Single log file
2. log file location specified in fapolicy-analyer.toml
3. Command line log level option
4. Design API w/eye towards journald integration
