### ISSUE TITLE
System trust filter is slow

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#684]
The search bar to filter the system trust list is very slow once there are any significant number of entries.

20K entries is a good number for example.

**Comment by egbicker** [comment]
@jw3 How would you feel about checking the number of entries in the system trust db when we start the app and if there are more than some threshold (5k?) we display a button where the list is. The button would have text along the lines of "There are a large number of entries in the db. Please begin a search or press this to display all entries". I think this would let us start a search without going through every row to check visibility until there are fewer entries or let the user know performance might suffer.

**Comment by jw3** [comment]
> display a button where the list is.

Sounds like something that would go with #520 rather than this one.

> short delay of 150 milliseconds 

This sounds familiar.  IIRC in gtk3 this cant be changed, in gtk4 it can.

If that was a 1 second delay it might make all the difference.

Two thoughts.
1. Simple - Disable the changed event and instead use Enter keystroke event. 
2. Less simple - Stash a last-updated-time in the widget and use that to manually manage delay.  It gets tricky at the last keystroke though.

I am wondering if (1) isn't just the best way until we see what changes as a result of #520.

?
