### ISSUE TITLE
Review the mode column in the analysis view

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#701]
It never seems to change from **R**WX

**Comment by egbicker** [comment]
@jw3 I think the issue might be in the rust backend. When the UI pulls from the `system.events` the only value present is "R" even when the details pane `stat` call suggests it should be something else. 

I traced it up from `__markup` in `object_list.load_store()` which is called from `policy_rules_admin_page`. Within that file the "R" as the mode value shows up in `on_next_system` when `self.__log` gets assigned. From there `__populate_objects` calls `__populate_list` which ends up calling `object_list.load_store`. I wonder if `parse_line` in `crates/trust/src/parse.rs` is maybe involved?

**Comment by jw3** [comment]
> I'll add a ticket for this new functionality and we can continue discussion there.

The tickets are  #740, #741 for the backend and frontend parts.

> Would take some backend work

Yep, too much to do right now.

>  Not sure if converting this will make 1.0, if not we will do a PR to at least remove the Mode column

The new functionality is going to have to wait, but I think for now lets do this, which sets the stage for the later work and addresses this ticket.

1. Frontend: Change the "Mode" header to "Perm"
2. Backend: Change mode to perm, possible values "any" "open" "exec"
