### ISSUE TITLE
Handle trust paths with spaces

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#74]
Paths in the trust db can have spaces, eg `launcher manifest.xml`

`/usr/lib/python3.8/site-packages/setuptools/command/launcher manifest.xml 628 c652db8d6ac1d35b4a0b4fa195590e2a48923dbccc9a5d9e38fb49fee7029db1`

**Comment by tparchambault** [comment]
I'm assuming the backend rust code can handle paths containing spaces currently, or should I consider that as also part of this ticket?

**Comment by dorschs57** [comment]
From the looks of this ticket I'd say @jw3 already tested the backend and its handling spaces correctly.  Ticket #88 looks like its to make sure the file chooser for the add button handles them correctly and adds them to the changeset to send to the backend.

**Comment by tparchambault** [comment]
Performed some testing to determine if paths with embedded spaces is an issue. The answer is 'yes'.

Test: Attempting to add the file: "File: /home/toma/Development/CTC/data space/man from mars.txt"
In Database: 
File: /home/toma/Development/CTC/data space/man from mars.txt
Size: 36
SHA256: 65d11d006895dead7ec4b253544299709e6cf2ecd6f1e28e454f6e20f5170b1c

On File System:
stat: cannot statx '/home/toma/Development/CTC/data': No such file or directory
stat: cannot statx 'space/man': No such file or directory
stat: cannot statx 'from': No such file or directory
stat: cannot statx 'mars.txt': No such file or directory
SHA256: 65d11d006895dead7ec4b253544299709e6cf2ecd6f1e28e454f6e20f5170b1c
