### ISSUE TITLE
On unsupported AWS Linux 2 platform: Initial read of Trust database fails.

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#765]
To emphasize, this issue has been observed on an unsupported platform, so priority can not be set lower... however someone might have seen this issue at some point and may save me some cycles.

The currently released version of AWS Linux 2 does not have an available `fapolicyd` package afaik consequently I built from src, and trying to localize the fapolicy-analyzer's start-up issue to either the daemon or the analyzer or a misconfiguration between the two.

The `fapolicyd` version is `1.1`, and built and installed via autotools, i.e. `configure, make, make install.` The source was directly downloaded from `wget --no-check-certificate http://people.redhat.com/sgrubb/fapolicyd/fapolicyd-1.1.tar.gz -O /usr/local/build/fapolicyd-1.1.tar.gz` as per `https://github.com/linux-application-whitelisting/fapolicyd/issues/180`

The console output when starting the fapolicy-analyzer in a development environment:

> --- Starting a fapolicy-analyzer development shell 
pipenv shell
Launching subshell in virtual environment...
 . /home/toma/.local/share/virtualenvs/fapolicy-analyzer-6GRQ6orK/bin/activate
[CORP\toma@a-2mmzeip754sx6 fapolicy-analyzer]$  . /home/toma/.local/share/virtualenvs/fapolicy-analyzer-6GRQ6orK/bin/activate
(fapolicy-analyzer) [CORP\toma@a-2mmzeip754sx6 fapolicy-analyzer]$ python -m fapolicy_analyzer.ui -v
DEBUG:root:Verbosity enabled.
DEBUG:root:Xdg absolute path: /home/toma/.local/state/fapolicy-analyzer/FaCurrentSession.tmp
DEBUG:root:SessionManager::set_autosave_filename: /home/toma/.local/state/fapolicy-analyzer/FaCurrentSession.tmp
fapolicy-analyzer v0.0.0+320.g3263f57
DEBUG:fapolicy_analyzer.redux._internal.feature:system
DEBUG:root:_PostInitCaller.__call__((), {})
thread '<unnamed>' panicked at 'failed to parse_strtyped_trust_record: ParseSizeError(ParseIntError { kind: Empty })', crates/trust/src/check.rs:46:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

TIA

**Comment by jw3** [comment]
Looks like a trust parse error.

What does the fapolicyd.trust and rules.d/* files look like?

Paste content of all of those here.

**Comment by tparchambault** [comment]
Thx @jw3  I'll give it a spin at some point. Would be cool if we get another functional platform out of the box.
