### ISSUE TITLE
Add config and log paths to rpm

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#768]
To ensure the config and log paths are accessible after rpm install they should be added to the rpm file list.

This likely eliminates xdg directories.

- /etc/fapolicy-analyzer/config.toml
- /var/log/fapolicy-analyzer.log

**Comment by jw3** [comment]
This would resolve #454

**Comment by jw3** [comment]
I think development environments will still use XDG.

**Comment by tparchambault** [comment]
Will use a command-line option (tentatively, `-x`, if unused) to specify the use of the default `xdg` locations, otherwise logs and config files will be located under `/var/log/` and `/etc/` respectively.

**Comment by jw3** [comment]
The rpm spec will get an entry like this for the config file

`%config(noreplace) %attr(644,root,%{name}) %{_sysconfdir}/%{name}/%{name}.conf`

and like this for the log file

`%ghost %attr(440,%{name},%{name}) %{_localstatedir}/log/%{name}.log`

**Comment by jw3** [comment]
The config file part should be straightforward.  It needs added to ensure it is trusted in an install out of the box.

Need to look closer at the log file aspect of this then, is there an existing rule for var log locations?  Like TA brought up, trust is not ideal for a log file.

**Comment by tparchambault** [comment]
Maybe `fapolicyd`'s log file entry in its spec file is somewhere in the ballpark:
> %ghost %attr(440,%{name},%{name}) %verify(not md5 size mtime) %{_localstatedir}/log/%{name}-access.log

**Comment by tparchambault** [comment]
Awaiting review/merge via @jw3
