### ISSUE TITLE
Profiler testing over Rhel86 observations

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#808]
## Summary ##

1. Directly invoking `fapolicyd --debug --permissive` outputs to stderr not stdout wrt Profiler Tool Target Output pane section titles.
2. Specifying a `user` w/o specifying a `working directory` sets the working directory to the `root` user's HOME.
3. Specifying only the basename of a target binary while specifying a working directory, and a `PATH` env var results in no output in the Profiler Tool Target Output pane

Please see https://github.com/ctc-oss/fapolicy-analyzer/pull/770 for details and images.

**Comment by jw3** [comment]
Thanks for these reports @tparchambault.  Couple of easy fixes for the first two in #809.  Third one is a good catch too, I'll add it to the same PR.

If you can pull the rpm from the PR and test it and let me know... _before_ I merge :wink:

**Comment by tparchambault** [comment]
Currently testing over RHEL86 w/latest CI rpm...

**Comment by jw3** [comment]
> The last observation... With a specified user and unspecified working directory, the target is executed in the root user's home directory. The first iteration used the specified user's home directory as its pwd in the event the profiling target performed relative file r/w operations.

https://github.com/ctc-oss/fapolicy-analyzer/pull/770#issuecomment-1456746192

@tparchambault I am testing v0.6.8 and it doesnt appear that this is implemented back there

Profile the `pwd` command as user dave and the output is `/root`

![image](https://user-images.githubusercontent.com/1545372/223527228-629e8c03-07fe-4cd6-a5df-28c058d10b0d.png)
