### ISSUE TITLE
Profiler output should be copy-friendly

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#810]
1. Allow text to be copied out of the output view
2. Print the arguments passed to the backend

Alternative to (1) is to add a copy button that selects all the output into the clipboard.

Use case: I want to quickly show someone what ran in the profiler without taking a screenshot.

**Comment by egbicker** [comment]
![image](https://user-images.githubusercontent.com/51774793/224080906-ee103a98-6500-4e61-96ad-212c2c8f884f.png)
@jw3 How does this look?

**Comment by jw3** [comment]
That looks good.

I wonder if a monospace font for the output view would improve things.  I like alignment...

Could try that in this PR.
