### ISSUE TITLE
Add additional build info to packaged application

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#823]
It would be useful to display additional build info on the About page.

- build environment
- build time
- git commit
- ...

Would make distinguishing between builds of same version from different source easier. Especially during testing where we have GitHub builds and Koji builds floating around.

**Comment by egbicker** [comment]
@jw3 Is there any way to add the git commit information to the spec file so that `rpm -qi fapolicy-analyzer` might be able to grab all the info from an RPM install?

**Comment by jw3** [comment]
In addition to the gui adds from our discussion I think there is value in following the idea of adding to the  spec too.   If possible, then we get  both ui and cli like TA wanted.
