### ISSUE TITLE
Ancillary Trust not reloaded after deployment rollback

### ISSUE THREAD

**Issue by dorschs57** [ctc-oss/fapolicy-analyzer#827]
If the Keep Changes countdown after a deployment is allowed to expire and trigger a rollback, the Ancillary Trust is not reloaded correctly in the view. If I start with an empty Ancillary Trust and add one trusted file then after rollback the list is empty and the status shows 0% loaded. If I start with files in the Ancillary Trust and add one more trusted file then after rollback the list shows the previously trusted files only. In both cases, if I select Trust from the Tool menu so the screen reloads the Ancillary Trust view reloads with the added file displayed.

To reproduce:
1. Add a trusted file to the Ancillary Trust
2. Deploy
3. Allow the Keep Changes countdown to expire and rollback
4. The Ancillary Trust view is not updated properly 
5. Select the Tool->Trust menu
6. The Ancillary Trust view refreshes with the correct files displayed

**Comment by dorschs57** [comment]
Confirmed the same issue happens if you just click No on the Keep Changes dialog instead of waiting for the timeout.

**Comment by jw3** [comment]
Possibly related to #736?
