### ISSUE TITLE
Document Rust backend public API

### ISSUE THREAD

**Issue by tparchambault** [ctc-oss/fapolicy-analyzer#83]
Pls generate the documentation for the public function bindings (and if not functional w/current status if possible, i.e. available for binding but not implemented, stubbed, etc)

**Comment by jw3** [comment]
As a workaround until we publish something you can

```
cd python
cargo doc
```

Then open `python/target/doc/fapolicy_analyzer_python/index.html` in a browser.

Ill take a pass and update the doc comments to provide more info.

**Comment by jw3** [comment]
Doc is applied to the bindings and commands to generate are provided, this should have been closed.
