### ISSUE TITLE
Upgrade pyo3

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#882]
We are currently holding back all versions for epel8 Python 3.6 abi support.  Could instead use the minimal abi and all versions could move forward to more recent Pyo3.

**Comment by decathorpe** [comment]
The old pyo3 version used in this project is now even more of a problem, because Python 3.12 (as available in Fedora 39+) is only correctly supported by pyo3 v0.19.2 and newer. Previous versions of pyo3 are potentially broken due to ABI changes in Python 3.12.

**Comment by jw3** [comment]
Reference: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/XG7GMDZFL2RO4QHEFBJKU7YDE3AZBRVM/#XG7GMDZFL2RO4QHEFBJKU7YDE3AZBRVM
