### ISSUE TITLE
Trust parsing broken at fapolicyd 1.3

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#885]
The file source type id was bumped from 2 to 3.

https://github.com/linux-application-whitelisting/fapolicyd/commit/a11516d65c3ac231ec4f73bc77025935c6b5fa0b#diff-19658911d20c597f6b5e2afdc5b1cd3d91d00edcb52294223a074d4e666d2accR31

**Comment by radosroka** [comment]
I consider this to be a bug.

**Comment by radosroka** [comment]
It's going to be fixed in https://github.com/linux-application-whitelisting/fapolicyd/pull/249.

**Comment by jw3** [comment]
Thanks @radosroka :+1:
