### ISSUE TITLE
Text editor state issues

### ISSUE THREAD

**Issue by jw3** [ctc-oss/fapolicy-analyzer#912]
The text editor views (rules, config) allow the user to navigate away from the editor while unsaved changes are present.  When the user navigates back the unsaved changes are gone.

The system does however appear to track some notion of the missing state, this is evident from the rules editor

1. Edit rule text
2. Navigate away without saving
3. Attempt to deploy from another view
4. Observe the unsaved rules dialog

![image](https://github.com/ctc-oss/fapolicy-analyzer/assets/1545372/9f33f283-0919-4aea-8a4a-ed9fd4f35af3)

**Comment by egbicker** [comment]
Is the intent to discard changes upon navigation? Perhaps the unsaved dialog should show up when attempting to navigate away with unsaved changes present and then discard them to avoid this dialog in other pages?

**Comment by jw3** [comment]
Yes adding an additional check and prompt when navigating away would be good.  If they leave, the changes get discarded.
